version: '3'

services:
  flask:
    build: .
    container_name: flask_app
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
